let aptsDb = db.collection( 'appointments' )
let profileDb = db.collection( 'profiles' )
let contentWrapper = document.querySelector( '.contentWrapper' )
let scheduleFilterMonth = document.querySelector( '.scheduleFilterMonth' )
let monthYearArr = document.querySelector( '.monthYearArr' )
let aptsRange = document.querySelector( '.aptsRange' )
let appointmentCount = document.querySelector( '.appointmentCount' )
let scheduleFilterStatus = document.querySelector( '.scheduleFilterStatus' )

let scheduleGalleryView = document.querySelector( '.scheduleGalleryView' ),
  updateTableView = document.querySelector( '.updateTableView' ),
  updateViewIcon = document.querySelector( '.updateViewIcon' ),
  galleryViewIcon = document.querySelector( '.galleryViewIcon' ),
  updateTableViewRows = document.querySelector( '.updateTableViewRows' ),
  updateAppointmentsSection = document.querySelector( '.updateAppointmentsSection' ),
  updateAppointments = document.querySelector( '.updateAppointments' ),
  completedViewIcon = document.querySelector( '.completedViewIcon' ),
  completedTableView = document.querySelector( '.completedTableView' ),
  cancelledViewIcon = document.querySelector( '.cancelledViewIcon' ),
  cancelledTableView = document.querySelector( '.cancelledTableView' ),
  completedTableViewRows = document.querySelector( '.completedTableViewRows' ),
  cancelledTableViewRows = document.querySelector( '.cancelledTableViewRows' )