let

  // Form Field Variables 
  aptName = document.querySelector( '.aptName' ),
  aptEmail = document.querySelector( '.aptEmail' ),
  aptMobileNumber = document.querySelector( '.aptMobileNumber' ),
  aptStartDate = document.querySelector( '.aptStartDate' ),
  aptDay = document.querySelector( '.aptDay' ),
  aptFees = document.querySelector( '.aptFees' ),
  aptType = document.querySelector( '.aptType' ),
  aptNature = document.querySelector( '.aptNature' ),
  aptAddress = document.querySelector( '.aptAddress' ),
  aptOccurrenceType = document.querySelector( '.aptOccurrenceType' ),
  aptCategory = document.querySelector( '.aptCategory' ),
  aptTimeSlot = document.querySelector( '.aptTimeSlot' ),
  createAptBtn = document.querySelector( '.createAptBtn' ),
  
  countryCode = document.querySelector( ".countryCode" ),
  dropOption = document.querySelector( ".dropOption" ),
  countryCodeNumber = document.querySelector( ".countryCodeNumber" ),

  // Emergency Contact variables
  emergencyName = document.querySelector( ".emergencyName" ),
  emergencyRelation = document.querySelector( ".emergencyRelation" ),
  emergencyAddress = document.querySelector( ".emergencyAddress" ),
  emergencyCountryCode = document.querySelector( ".emergencyCountryCode" ),
  emergencyMobileNumber = document.querySelector( ".emergencyMobileNumber" ),

  // Occurrence is 2
  firstDaySlot = document.querySelector( '.firstDaySlot' ),
  firstDaySlotWrapper = document.querySelector( '.firstDaySlotWrapper' ),
  firstStartDate = document.querySelector( '.firstStartDate' ),
  firstStartDateWrapper = document.querySelector( '.firstStartDateWrapper' ),
  firstTimeSlotWrapper = document.querySelector( '.firstTimeSlotWrapper' ),
  firstTimeSlot = document.querySelector( '.firstTimeSlot' ),
  createTwoAptBtn = document.querySelector( '.createTwoAptBtn' ),
  cancelForOccurrence = document.querySelector( '.cancelForOccurrence' ),
  editButton = document.querySelector( '.editButton' ),

  // Confirm Page Variables
  confirmPage = document.querySelector( '.confirmPage' ),
  confirmName = document.querySelector( '.confirmName' ),
  confirmEmail = document.querySelector( '.confirmEmail' ),
  confirmMobileNumber = document.querySelector( '.confirmMobileNumber' ),
  confirmDay = document.querySelector( '.confirmDay' ),
  confirmStartDate = document.querySelector( '.confirmStartDate' ),
  confirmTimeSlot = document.querySelector( '.confirmTimeSlot' ),
  confirmAppointmentType = document.querySelector( '.confirmAppointmentType' ),
  confirmAppointmentNature = document.querySelector( '.confirmAppointmentNature' ),
  confirmOccurrenceType = document.querySelector( '.confirmOccurrenceType' ),
  confirmAddress = document.querySelector( '.confirmAddress' ),
  confirmCategory = document.querySelector( '.confirmCategory' ),
  confirmFees = document.querySelector( '.confirmFees' ),
  confirmButton = document.querySelector( '.confirmButton' ),
  completed = document.querySelector( '.completed' ),
  scheduled = document.querySelector( '.scheduled' ),
  confirmSecondStartDate = document.querySelector( ".confirmSecondStartDate" ),
  confirmSecondDay = document.querySelector( ".confirmSecondDay" ),
  confirmCountryCode = document.querySelector( ".confirmCountryCode" ),
  confirmDropOption = document.querySelector( ".confirmDropOption" ),
 
  confirmEmergencyName = document.querySelector( ".confirmEmergencyName" ),
  confirmEmergencyRelation = document.querySelector( ".confirmEmergencyRelation" ),
  confirmEmergencyAddress = document.querySelector( ".confirmEmergencyAddress" ),
  confirmEmergencyCountryCode = document.querySelector( ".confirmEmergencyCountryCode" ),
  confirmEmergencyMobileNumber = document.querySelector( ".confirmEmergencyMobileNumber" ),
  confirmSecondTimeSlot = document.querySelector( ".confirmSecondTimeSlot" )