let sectionButton = document.querySelectorAll( ".sectionButton" ),
  workContent = document.querySelector( ".workContent" ),
  profileSection = document.querySelector( '.profileSection' ),
  reportByName = document.querySelector( '.reportByName' ),
  downArrow = document.querySelector( ".downArrow" ),
  reportByNameFilter = document.querySelector( ".reportByNameFilter" ),
  totalSessionsCount = document.querySelector( ".totalSessionsCount" ),
  totalScheduledCount = document.querySelector( ".totalScheduledCount" ),
  totalSupervisionCount = document.querySelector( ".totalSupervisionCount" ),
  totalFreeCancelledCounts = document.querySelector( ".totalFreeCancelledCount" ),
  totalPaidCancelledCounts = document.querySelector( ".totalPaidCancelledCount" ),
  totalRescheduledCount = document.querySelector( ".totalRescheduledCount" ),
  totalPendingCount = document.querySelector( ".totalPendingCount" )



let nameOfUser = document.querySelector( ".name" ),
  email = document.querySelector( ".email" ),
  mobileNumber = document.querySelector( ".mobileNumber" ),
  createDate = document.querySelector( ".createDate" ),
  fee = document.querySelector( ".fee" ),
  category = document.querySelector( ".category" ),
  occurrence = document.querySelector( ".occurrence" ),
  address = document.querySelector( ".address" ),
  slot = document.querySelector( ".slot" ),
  profile = document.querySelector( '.profile' ),
  whatChanged = document.querySelector( '.whatChanged' ),
  e_name = document.querySelector( '.e_name' ),
  e_relation = document.querySelector( '.e_relation' ),
  e_mobileNumber = document.querySelector( '.e_mobileNumber' ),
  e_address = document.querySelector( '.e_address' ),
  profileUpdatedOn = document.querySelector( ".profileUpdatedOn" )